Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,27 +4,35 @@ on:
   pull_request:
 
 jobs:
-  test:
-    name: PR Greeting
-    permissions:
-      pull-requests: write
+  parse_jira_story_number:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/github-script@v6
-        with:
-          script: |
-          
-            const title = context.payload.pull_request.title;
-            const match = title.match(/(mob|uet)\s*([\w-]+)/i);
-            if (match) {
-                const ticketNumber = match[2].replace(/\s/g, "-");
-                const jiraTicketLink = `https://your_organization.atlassian.net/browse/${ticketNumber}`;
-                let description = context.payload.pull_request.body ?? ``;
-                description = `${description}\nJira ticket: ${jiraTicketLink}`;
-                github.rest.pulls.update({
-                    owner: context.repo.owner,
-                    repo: context.repo.repo,
-                    pull_number: context.payload.pull_request.number,
-                    body: description
-                });
-            }
+      - name: Extract Jira Story Number
+        id: extract_jira_story_number
+        run: |
+          # Get the branch name
+          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
+
+          # Extract Jira story number using regex
+          if [[ $branch_name =~ ([A-Za-z]+-[0-9]+) ]]; then
+            jira_story_number="${BASH_REMATCH[1]}"
+          else
+            echo "Jira story number not found in branch name"
+            exit 1
+          fi
+
+          echo "::set-output name=jira_story_number::$jira_story_number"
+
+      - name: Append Jira Story Number to PR Description
+        run: |
+          jira_story_number="${{ steps.extract_jira_story_number.outputs.jira_story_number }}"
+          pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
+          current_description=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
+
+          updated_description="${current_description%\"}\n\n**Jira Story Number:** $jira_story_number\""
+
+          curl -X PATCH \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -d "{\"body\": \"$updated_description\"}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"
